# Generated by Django 2.1.2 on 2018-11-03 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sprinter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name_plural': 'stories'},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_title',
            new_name='title',
        ),
    ]
