# Generated by Django 2.1.2 on 2018-11-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sprinter', '0002_auto_20181103_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='estimation',
            field=models.FloatField(default=0.5),
        ),
    ]
